
services:
  app:
    build: .
    container_name: bewise_test_app
    ports:
      - 8000:8000
    depends_on:
      - postgres
    networks:
      - app

  postgres:
    image: postgres:17-alpine
    container_name: bewise_test_postgres
    volumes:
      - ./.postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - app

networks:
  app:
    driver: bridge

volumes:
  .postgres_data:
